# Generated by Django 4.1.5 on 2023-05-01 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("url", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "profile_info",
                    models.TextField(blank=True, max_length=150, null=True),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pictures",
                        verbose_name="Picture",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
